index.md

Update the index page

---

.travis.yml

Build page in CI

---

_config.yml
_layouts/default.html

Update website config

---

assets/Caesar_cipher_left_shift_of_3.svg
assets/ROT13_table_with_example.svg
index.md

Added first draft of Caesar Cipher

---

.travis.yml
scripts/caesar.py
tests/test_caesar.py

Added script encrypt/decrypt with Caesar cipher

---

scripts/caesar.py

Read from standard input

---

scripts/caesar.py
tests/test_caesar.py

Expand characters shifted by Caesar cipher

---

scripts/caesar.py
tests/test_caesar.py

Add more characters to cipher

---

scripts/caesar.py

Wrap lines at 80 characters width

---

index.md

Add Caesar Cipher Challenge

---

index.md

Remove table

---

assets/Caesar_cipher_left_shift_of_3.svg
assets/ROT13_table_with_example.svg

Update image background

---

index.md

Small update to challenge description

---

assets/Caesar_cipher_left_shift_of_3.svg
assets/ROT13_table_with_example.svg

Scale images to the same size

---

index.md

Fix indentation

---

index.md
template.md

Add solution template

---

setup.py
tox.ini

Add setuptools and some tox testing

---

scripts/frequency_analysis.py

Adding script to run a frequency analysis on a ciphertext

---

.travis.yml
scripts/frequency_analysis.py
tox.ini

Add tests to Travis-CI

---

.circleci/config.yml
tox.ini

Add configuration for Circleci

---

index.md

Add Circleci status badge

---

index.md

Small formatting fix

---

.circleci/config.yml

Fix failing Circleci webpage builds

Switch containers for webpage build

---

scripts/caesar.py

Add file input option to `caesar.py`

---

scripts/frequency_analysis.py
tox.ini

Add frequency script

---

scripts/frequency_analysis.py

Update help text

---

.circleci/config.yml

Add cache for webpage builds

---

_layouts/default.html

Update adsense script

---

assets/English_letter_frequency_(frequency).svg
index.md

Add description of frequency analysis

---

Challenge1_adis.md

HI!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

soulution for challange1

---

scripts/caesar.py
scripts/vigenere.py

Add more characters to be ignored
